# Machine Learning Classificação
## Continuação

In [1]:
import pandas as pd
dados = pd.read_excel('dados_vinho_tratado.xlsx')
dados

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0          0.297521          0.413333     0.000000        0.019939   0.111296   
1          0.330579          0.533333     0.000000        0.030675   0.147841   
2          0.330579          0.453333     0.024096        0.026074   0.137874   
3          0.611570          0.133333     0.337349        0.019939   0.109635   
4          0.297521          0.413333     0.000000        0.019939   0.111296   
...             ...               ...          ...             ...        ...   
6492       0.198347          0.086667     0.174699        0.015337   0.049834   
6493       0.231405          0.160000     0.216867        0.113497   0.063123   
6494       0.223140          0.106667     0.114458        0.009202   0.053156   
6495       0.140496          0.140000     0.180723        0.007669   0.021595   
6496       0.181818          0.086667     0.228916        0.003067   0.018272   

      free_sulfur_dioxide  total_sulfur_dioxide   density        ph  \
0                0.034722              0.064516  0.206092  0.612403   
1                0.083333              0.140553  0.186813  0.372093   
2                0.048611              0.110599  0.190669  0.418605   
3                0.055556              0.124424  0.209948  0.341085   
4                0.034722              0.064516  0.206092  0.612403   
...                   ...                   ...       ...       ...   
6492             0.079861              0.198157  0.077694  0.426357   
6493             0.194444              0.373272  0.150183  0.333333   
6494             0.100694              0.241935  0.104685  0.209302   
6495             0.065972              0.239631  0.030461  0.480620   
6496             0.072917              0.211982  0.044342  0.418605   

      sulphates   alcohol  type_red  type_white  quality  
0      0.191011  0.202899         1           0        0  
1      0.258427  0.260870         1           0        0  
2      0.241573  0.260870         1           0        0  
3      0.202247  0.260870         1           0        0  
4      0.191011  0.202899         1           0        0  
...         ...       ...       ...         ...      ...  
6492   0.157303  0.463768         0           1        0  
6493   0.134831  0.231884         0           1        0  
6494   0.134831  0.202899         0           1        0  
6495   0.089888  0.695652         0           1        1  
6496   0.056180  0.550725         0           1        0  

[6497 rows x 14 columns]

### Separação dos dados em x e y
Daqui em diante, é importante ter em mente que o nome das colunas será perdido

In [2]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed_acidity         6497 non-null   float64
 1   volatile_acidity      6497 non-null   float64
 2   citric_acid           6497 non-null   float64
 3   residual_sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free_sulfur_dioxide   6497 non-null   float64
 6   total_sulfur_dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   ph                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  type_red              6497 non-null   int64  
 12  type_white            6497 non-null   int64  
 13  quality               6497 non-null   int64  
dtypes: float64(11), int64(3)
memory usage: 710.7 KB


In [3]:
x = dados.iloc[:,:13].values
y = dados.iloc[:,13].values

In [4]:
x.shape,y.shape

((6497, 13), (6497,))

### Separação da base em treino e teste

In [5]:
from sklearn.model_selection import train_test_split
x_treino,x_teste,y_treino,y_teste = train_test_split(x,y,train_size=0.8,random_state=42)

In [6]:
x_treino.shape,y_treino.shape

((5197, 13), (5197,))

In [7]:
x_teste.shape,y_teste.shape

((1300, 13), (1300,))

Averiguando a distribuição de classes antes e depois da separação:

In [8]:
import numpy as np
# Base original
unique_values, counts = np.unique(y, return_counts=True)
prop = counts/y.size
print(unique_values,counts,prop)

[0 1] [5220 1277] [0.80344775 0.19655225]


In [9]:
# Base de treino
unique_values, counts = np.unique(y_treino, return_counts=True)
prop = counts/y_treino.size
print(unique_values,counts,prop)

[0 1] [4172 1025] [0.80277083 0.19722917]


In [10]:
# Base de teste
unique_values, counts = np.unique(y_teste, return_counts=True)
prop = counts/y_teste.size
print(unique_values,counts,prop)

[0 1] [1048  252] [0.80615385 0.19384615]


A função ```train_test_split``` é fundamental, pois tenta manter a proporção das classes nas bases de treino e teste iguais a proporção das classes na base original

## Algoritmos de Machine Learning de Classificação
* Naive Bayes
* Árvore de decisão
* Random Forest
* KNN
* Regressão Logística
* SVM
* Redes Neurais

### Naive Bayes

Algoritmo baseados em probabilidade pura, determinístico

![Alt text](image.png)

In [11]:
from sklearn.naive_bayes import GaussianNB
modelo = GaussianNB()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


In [12]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64))

In [13]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64))

### Árvore de decisão

Define uma árvore de regras.

![Alt text](image-5.png)

In [14]:
from sklearn.tree import DecisionTreeClassifier
modelo = DecisionTreeClassifier()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


In [15]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [16]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1], dtype=int64))

### Random Forest

Define várias árvores de regras sob diferentes circunstâncias, com diferentes inicializações, etc... e seleciona o resultado por votação entre as árvores

![Alt text](image-6.png)

In [17]:
from sklearn.ensemble import RandomForestClassifier
modelo = RandomForestClassifier()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


In [18]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64))

In [19]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64))

### KNN

Algoritmo baseado em proximidade entre os valores

![Alt text](image-7.png)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
modelo = KNeighborsClassifier()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


In [21]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [22]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64))

### Suport Vector Machine

Tenta definir uma fronteira entre os dados de uma classe e outra

![Alt text](image-8.png)

In [23]:
from sklearn.svm import SVC
modelo = SVC()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


In [24]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [25]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

### Regressão Logística

Embora exista "regressão", é um algoritmo de classificação.

É baseado em probabilidade, mas ajusta uma função cumulativa de probabilidade ao dados.

![Alt text](image-9.png)

In [26]:
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


In [27]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [28]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64))

### Redes neurais artificiais

![Alt text](image-10.png)

In [29]:
from sklearn.neural_network import MLPClassifier
modelo = MLPClassifier()
modelo.fit(x_treino,y_treino)
y_previsto = modelo.predict(x_teste)


d:\Drive Unesc\Meu Drive\2023-2\5af - Ciência de Dados\Notebooks\Unidade 3\venv\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [30]:
y_teste[:10],y_previsto[:10]

(array([1, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64))

In [31]:
y_teste[-10:],y_previsto[-10:]

(array([0, 0, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64))